language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt update
  - sudo apt install libportaudio2
cache: pip
install:
  - pip install --upgrade tox-travis virtualenv
script: tox